version: "3.9"

networks:
  proxy:
    driver: overlay
    external: false
  internal:
    driver: overlay
    external: false

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/pgdata/postgres-data
  dbinit:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/deploy/db
  redisdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/pgdata/redis-data
  traefik-cert: {}
  client-static: {}

secrets:
  pg_password:
    external: true
  redis_password:
    external: true
  firebase_sa:
    file: /root/deploy/firebase-service-account.json

services:
  traefik:
    image: traefik:v3.1
    command:
      - --log.level=INFO
      - --api.dashboard=true

      # Use Swarm provider
      - --providers.swarm=true
      - --providers.swarm.endpoint=unix:///var/run/docker.sock
      - --providers.swarm.network=eventmap_proxy

      # Entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

      # HTTP->HTTPS redirect
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https

      # Let's Encrypt
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.le.acme.email=${EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    ports:
      - target: 80
        published: 80
        mode: ingress
      - target: 443
        published: 443
        mode: ingress
    volumes:
      - traefik-cert:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
      - internal
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.${DOMAIN}`)"
        - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
        - "traefik.http.routers.traefik-dashboard.tls.certresolver=le"
        - "traefik.http.routers.traefik-dashboard.service=api@internal"
        
        # WWW redirect middleware
        - "traefik.http.middlewares.www-redirect.redirectregex.regex=^https?://${DOMAIN}/(.*)"
        - "traefik.http.middlewares.www-redirect.redirectregex.replacement=https://www.$${DOMAIN}/$$1"
        - "traefik.http.middlewares.www-redirect.redirectregex.permanent=true"
        
        # Router for non-www to www redirect
        - "traefik.http.routers.to-www.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.to-www.entrypoints=websecure"
        - "traefik.http.routers.to-www.tls.certresolver=le"
        - "traefik.http.routers.to-www.middlewares=www-redirect"
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
      POSTGRES_DB: eventsdb
      PGDATA: /var/lib/postgresql/data/pgdata
    secrets: [pg_password]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - dbinit:/docker-entrypoint-initdb.d:ro   
    networks: [internal]
    deploy:
      placement: { constraints: [node.role == manager] }
      restart_policy: { condition: any, delay: 5s, max_attempts: 3 }
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d eventsdb -h 127.0.0.1 -p 5432 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 120s

  redis:
    image: redis:7-alpine
    command: >
      sh -c '
        PASS_FILE="/run/secrets/redis_password";
        PASS=$$(cat "$$PASS_FILE");
        exec redis-server \
          --appendonly yes \
          --appendfsync everysec \
          --dir /data \
          --save 900 1 --save 300 10 --save 60 10000 \
          --maxmemory 200mb --maxmemory-policy allkeys-lru \
          --requirepass "$$PASS";
      '
    networks: [internal]
    volumes:
      - redisdata:/data
    deploy:
      restart_policy: { condition: any, delay: 5s, max_attempts: 3 }
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M
      placement: { constraints: [node.role == manager] }
    healthcheck:
      test:
      - CMD-SHELL
      - >
        REDIS_PASS=$$(cat /run/secrets/redis_password 2>/dev/null || true);
        redis-cli -a "$$REDIS_PASS" PING | grep PONG;
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 15s
    secrets:
      - redis_password

  api:
    image: ghcr.io/shang8024/dynamic-event-map-api:latest
    environment:
      NODE_ENV: production             
      PORT: "${BACKEND_PORT}"          
      DB_HOST: db
      DB_PORT: "${DB_PORT:-5432}"     
      DB_NAME: "${DB_NAME:-eventsdb}"
      DB_USER: "${DB_USER:-user}"
      REDIS_HOST: redis
      REDIS_PORT: "${REDIS_PORT:-6379}"
      DB_PASSWORD_FILE: /run/secrets/pg_password
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
      ALLOWED_ORIGINS: "https://dynamic-event-map.cloud,https://www.dynamic-event-map.cloud"
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/firebase-service-account.json
      FRONTEND_PORT: 443
    secrets:
      - pg_password
      - redis_password
      - source: firebase_sa
        target: firebase-service-account.json
    networks: [proxy, internal]
    depends_on: [db, redis]
    deploy:
      replicas: 2
      update_config: { order: start-first }
      restart_policy: { condition: any }
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 128M
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=eventmap_proxy"
        - "traefik.http.routers.api.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)"
        - "traefik.http.routers.api.entrypoints=websecure"
        - "traefik.http.routers.api.tls.certresolver=le"
        - "traefik.http.routers.api.priority=10"
        - "traefik.http.middlewares.api-strip.stripprefixregex.regex=/api"
        - "traefik.http.routers.api.middlewares=api-strip"
        - "traefik.http.services.api.loadbalancer.server.port=5000"
        - "traefik.http.services.api.loadbalancer.sticky.cookie=true"
        - "traefik.http.services.api.loadbalancer.sticky.cookie.name=sio_sticky"
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 ${BACKEND_PORT} || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 6
      start_period: 30s

  client:
    image: ghcr.io/shang8024/dynamic-event-map-client:latest
    networks: [proxy]
    depends_on: [api]
    deploy:
      replicas: 1
      update_config: { order: start-first, parallelism: 1, delay: 5s }
      restart_policy: { condition: any, delay: 5s, max_attempts: 3 }
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=eventmap_proxy"
        - "traefik.http.routers.client.rule=Host(`www.${DOMAIN}`)"
        - "traefik.http.routers.client.entrypoints=websecure"
        - "traefik.http.routers.client.tls.certresolver=le"
        - "traefik.http.routers.client.priority=5"
        - "traefik.http.services.client.loadbalancer.server.port=80"
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1/ >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 6
      start_period: 10s

  events_ingest:
    image: ghcr.io/shang8024/dynamic-event-map-events-ingest:latest
    secrets:
      - pg_password
      - redis_password
    environment:
      DB_HOST: db
      DB_PORT: "${DB_PORT:-5432}"
      DB_NAME: "${DB_NAME:-eventsdb}"
      DB_USER: "${DB_USER:-user}"
      REDIS_HOST: redis
      REDIS_PORT: "${REDIS_PORT:-6379}"
      DB_PASSWORD_FILE: /run/secrets/pg_password
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
    depends_on: [db, redis]
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 0
      restart_policy:
        condition: none